---
title: "Trends in solar power generation"
output: html_notebook
---

Solar power generation has a strong seasonal component, dipping during the winter and peaking during the summer, which can obscure growth in solar power. This plot shows the growth trends by state in solar energy (kMWh of generated power), decomposed from the seasonal component of the time series. These data were gathered from the EIA-923 reports on plant-level power generation. Five states are highlighted as interesting examples of growth trends.

```{r results = FALSE, warning = FALSE, fig.width = 10, fig.height = 5}
library(tidyverse)
library(ggrepel)
library(lubridate)

solartrendsdf <- read.csv("../solar_trends.csv")

solartrendsdf <- solartrendsdf %>%
  mutate(Highlight = ifelse(State == "CA" | State == "NC" | State == "TX" | State == "NV" | State == "FL", State, NA),
         Date = parse_date_time(Date, orders = "Ymd"))

ggplot(data = solartrendsdf) + 
  geom_line(aes(Date, kMWh, group = State, color = Highlight, size = !is.na(Highlight), alpha = !is.na(Highlight))) +
  geom_label_repel(data = solartrendsdf %>% filter(!is.na(kMWh)) %>% filter(Date == last(Date), !is.na(Highlight)), aes(Date, kMWh, label = Highlight), nudge_x = 1e7, na.rm = TRUE) + 
  scale_size_manual(values=c(0.5, 1.5), guide = 'none') +
  scale_alpha_manual(values=c(0.5, 1), guide = 'none') + 
  guides(color = FALSE) +
  xlab("Year") +
  ylab("Power generated (kMWh)") +
  ggtitle("State-level trends in solar power generation")

```

California is the clear outlier, having heavily invested early in clean energy and continuing to expand its capacity. North Carolina and Nevada present a good opportunity for a policy case study: their initial growth was very similar, but North Carolina has continued to expand its solar power generation while Nevada has plateaued over the past few years. Florida and Texas have only recently begun to expand their solar power generation capacity, and they are both in zones of high solar radiation, making them prime targets for investment. 