---
title: "Renewable power capacity"
output: html_notebook
---

Based on EIA-860 data from 2019, this map shows the locations and capacities of power plants using solar- and wind-based power. The size of the circle shows the generator nameplate capacity, and the color indicates power-type (solar: gold; wind: gray). The location of the generators is derived from geographic coordinates provided by utility reporting. 

```{r results = FALSE, warning = FALSE, fig.width = 12, fig.height = 6}
library(tidyverse)
library(ggmap)
library(maps)
library(mapdata)

wind19loc <- read.csv("../wind_locations_2019.csv")
solar19loc <- read.csv("../solar_locations_2019.csv")
states <- map_data("state")

ggplot() + 
  geom_polygon(data = states, aes(long, lat, group = group), color = "black", fill = "white") +
  geom_point(data = solar19loc, aes(Longitude, Latitude, size = Nameplate.Capacity..MW.), alpha = 0.1, color = "gold") +
  geom_point(data = wind19loc, aes(Longitude, Latitude, size = Nameplate.Capacity..MW.), alpha = 0.1, color = "gray") +
  coord_fixed(1.3) +
  scale_x_continuous(limits=c(-130, -60)) +
  scale_y_continuous(limits = c(20, 50)) +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(size = "Capacity (MW)") +
  ggtitle("Distribution of wind (gray) and solar (gold) power plants in the contiguous United States")

```

The map shows clear regional differences in clean energy types, with only a few cities in California showing significant investment in both types of energy. Correlation of these data with wind pattern data may explain some of the differences, especially through the center of the country, but stark differences between contiguous states, such as Minnesota/Iowa, Virginia/North Carolina, and Massachusetts/Connecticut suggest the impact of local policy initiatives on clean energy investment.